# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: StingRay
email: 
description: > # this means to ignore newlines until "baseurl:"
    Stingray is a new software for X-ray timing and spectral timing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Stingray.github.io" # the base hostname & protocol for your site
twitter_username: stingray
github_username:  stingray

# Build settings
markdown: kramdown
